name: skynet_app
description: Minimal Skynet app - file browser, PDF viewer, bookmarks
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^5.2.7
  permission_handler: ^10.4.0
  flutter_pdfview: ^1.2.7
  shared_preferences: ^2.1.1
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
